<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use LobLib\Controllers\BillingGroupsController;
use LobLib\Exceptions;
use LobLib\Models;

class BillingGroupsControllerTest extends BaseTestController
{
    /**
     * @var BillingGroupsController BillingGroupsController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getBillingGroupsController();
    }

    public function testBillingGroupsList()
    {
        // Parameters for the API call
        $limit = 10;
        $offset = 0;
        $mInclude = null;
        $dateCreated = null;
        $dateModified = null;
        $sortBy = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->billingGroupsList(
                $limit,
                $offset,
                $mInclude,
                $dateCreated,
                $dateModified,
                $sortBy
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"data":[{"id":"bg_d5a5a89da9106f8","description":"Test billing_group","metada' .
                'ta":{},"date_created":"2019-07-27T23:49:01.511Z","date_modified":"2019-07-27T23' .
                ':49:01.511Z","object":"billing_group"},{"id":"bg_59b2150ae120887","description"' .
                ':"Test billing_group","metadata":{},"date_created":"2019-03-29T10:22:34.642Z","' .
                'date_modified":"2019-03-29T10:22:34.642Z","object":"billing_group"}],"object":"' .
                'list","next_url":null,"prev_url":null,"count":2}'
            )))
            ->assert();
    }

    public function testBillingGroupCreate()
    {
        // Parameters for the API call
        $body = TestParam::object(
            '{"name":"Marketing Dept","description":"Usage group used for the Marketing Dept resource sends"}',
            Models\BillingGroupEditable::class
        );

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->billingGroupCreate($body);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['ratelimit-limit'] = ["", false];
        $headers['ratelimit-remaining'] = ["", false];
        $headers['ratelimit-reset'] = ["", false];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"id":"bg_c94e83ca2cd5121","name":"Marketing Dept","description":"Usage group ' .
                'used for the Marketing Dept resource sends","date_created":"2017-11-07T22:56:10' .
                '.962Z","date_modified":"2017-11-07T22:56:10.962Z","object":"billing_group"}'
            )))
            ->assert();
    }
}
