<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Tests\Controllers;

use LobLib\Controllers\ChecksController;
use LobLib\Exceptions;

class ChecksControllerTest extends BaseTestController
{
    /**
     * @var ChecksController ChecksController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getChecksController();
    }

    public function testChecksList()
    {
        // Parameters for the API call
        $limit = 10;
        $beforeAfter = null;
        $mInclude = null;
        $dateCreated = null;
        $metadata = null;
        $scheduled = null;
        $sendDate = null;
        $mailType = null;
        $sortBy = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->checksList(
                $limit,
                $beforeAfter,
                $mInclude,
                $dateCreated,
                $metadata,
                $scheduled,
                $sendDate,
                $mailType,
                $sortBy
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }
}
