<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Tests\Controllers;

use Core\TestCase\BodyMatchers\KeysBodyMatcher;
use Core\TestCase\TestParam;
use LobLib\Controllers\PostcardsController;
use LobLib\Exceptions;
use LobLib\Models;

class PostcardsControllerTest extends BaseTestController
{
    /**
     * @var PostcardsController PostcardsController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getPostcardsController();
    }

    public function testPostcardsList()
    {
        // Parameters for the API call
        $limit = 10;
        $beforeAfter = null;
        $mInclude = null;
        $dateCreated = null;
        $metadata = null;
        $size = null;
        $scheduled = null;
        $sendDate = null;
        $mailType = null;
        $sortBy = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->postcardsList(
                $limit,
                $beforeAfter,
                $mInclude,
                $dateCreated,
                $metadata,
                $size,
                $scheduled,
                $sendDate,
                $mailType,
                $sortBy
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"data":[{"id":"psc_208e45e48d271294","description":null,"metadata":{},"to":{"' .
                'id":"adr_210a8d4b0b76d77b","description":null,"name":"LEORE AVIDAR","company":n' .
                'ull,"phone":null,"email":null,"address_line1":"210 KING ST STE 6100","address_l' .
                'ine2":null,"address_city":"SAN FRANCISCO","address_state":"CA","address_zip":"9' .
                '4107-1741","address_country":"UNITED STATES","metadata":{},"date_created":"2018' .
                '-12-08T03:01:07.651Z","date_modified":"2018-12-08T03:01:07.651Z","object":"addr' .
                'ess"},"url":"https://lob-assets.com/postcards/psc_208e45e48d271294.pdf?version=' .
                'v1&expires=1619218302&signature=NfHHLBSr5tOHA_Z4kij4dKqZG8f3vMDtwvuFVeeF9pV_lyl' .
                'cjLsVVODhNCE5hR6-2slUr6t9WMNsi429Pj7_DA","carrier":"USPS","front_template_id":n' .
                'ull,"back_template_id":null,"front_template_version_id":null,"back_template_ver' .
                'sion_id":null,"date_created":"2021-03-24T22:51:42.838Z","date_modified":"2021-0' .
                '3-24T22:51:42.838Z","send_date":"2021-03-24T22:51:42.838Z","use_type":"marketin' .
                'g","object":"postcard"},{"id":"psc_0e03d1ad7d31f151","description":null,"metada' .
                'ta":{},"to":{"id":"adr_c7cb63d68f8d6","description":null,"name":"JANE DOE","com' .
                'pany":"LOB","phone":"5555555555","email":"jane.doe@lob.com","address_line1":"37' .
                '0 WATER ST","address_line2":"","address_city":"SUMMERSIDE","address_state":"PE"' .
                ',"address_zip":"C1N 1C4","address_country":"CANADA","metadata":{},"date_created' .
                '":"2018-12-08T03:01:07.651Z","date_modified":"2018-12-08T03:01:07.651Z","object' .
                '":"address","recipient_moved":false},"from":{"id":"adr_210a8d4b0b76d77b","descr' .
                'iption":null,"name":"LEORE AVIDAR","company":null,"phone":null,"email":null,"ad' .
                'dress_line1":"210 KING ST STE 6100","address_line2":null,"address_city":"SAN FR' .
                'ANCISCO","address_state":"CA","address_zip":"94107-1741","address_country":"UNI' .
                'TED STATES","metadata":{},"date_created":"2018-12-08T03:01:07.651Z","date_modif' .
                'ied":"2018-12-08T03:01:07.651Z","object":"address"},"url":"https://lob-assets.c' .
                'om/postcards/psc_208e45e48d271294.pdf?version=v1&expires=1619218302&signature=N' .
                'fHHLBSr5tOHA_Z4kij4dKqZG8f3vMDtwvuFVeeF9pV_lylcjLsVVODhNCE5hR6-2slUr6t9WMNsi429' .
                'Pj7_DA","carrier":"USPS","front_template_id":null,"back_template_id":null,"fron' .
                't_template_version_id":null,"back_template_version_id":null,"tracking_events":[' .
                '],"size":"6x11","mail_type":"usps_first_class","merge_variables":{},"thumbnails' .
                '":[{"small":"https://lob-assets.com/letters/ltr_4868c3b754655f90_thumb_small_1.' .
                'png?expires=1540372221&signature=a5fRBJ22ZA78Vgpg34M9UfmHWTS3eha","medium":"htt' .
                'ps://lob-assets.com/letters/ltr_4868c3b754655f90_thumb_medium_1.png?expires=154' .
                '0372221&signature=bAzL8sv935PY09FWSkpDpWKkyvGSWYF","large":"https://lob-assets.' .
                'com/letters/ltr_4868c3b754655f90_thumb_large_1.png?expires=1540372221&signature' .
                '=gsKvxXgrm4v4iZD3bOibK7jApNkEMdW"}],"expected_delivery_date":"2021-03-30","date' .
                '_created":"2021-03-24T22:51:42.838Z","date_modified":"2021-03-24T22:51:42.838Z"' .
                ',"send_date":"2021-03-24T22:51:42.838Z","use_type":"marketing","object":"postca' .
                'rd"}],"object":"list","previous_url":null,"next_url":null,"count":2}'
            )))
            ->assert();
    }

    public function testPostcardCreate()
    {
        // Parameters for the API call
        $body = TestParam::object(
            '{"description":"demo","to":{"description":"Harry - Office","name":"Harry Zhang","c' .
            'ompany":"Lob","email":"harry@lob.com","phone":"5555555555","address_line1":"210 Kin' .
            'g St","address_line2":"# 6100","address_city":"San Francisco","address_state":"CA",' .
            '"address_zip":"94107","address_country":"US"},"from":{"description":"Harry - Office' .
            '","name":"Harry Zhang","company":"Lob","email":"harry@lob.com","phone":"5555555555"' .
            ',"address_line1":"210 King St","address_line2":"# 6100","address_city":"San Francis' .
            'co","address_state":"CA","address_zip":"94107","address_country":"US"},"front":"tmp' .
            'l_a1234dddg","back":"tmpl_a1234dddg","size":"6x9","mail_type":"usps_first_class","m' .
            'erge_variables":{"name":"Harry"},"metadata":{"spiffy":"true"},"send_date":"2017-11-' .
            '01T00:00:00.000Z","use_type":"marketing","qr_code":{"position":"relative","redirect' .
            '_url":"https://www.lob.com","width":"2.5","top":"2.5","right":"2.5","pages":"front,' .
            'back"}}',
            Models\PostcardEditable::class
        );
        $idempotencyKey = '026e7634-24d7-486c-a0bb-4a17fd0eebc5';
        $idempotencyKey2 =
            '026e7634-24d7-486c-a0bb-4a17fd0eebc5';

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->postcardCreate($body, $idempotencyKey, $idempotencyKey2);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['ratelimit-limit'] = ["", false];
        $headers['ratelimit-remaining'] = ["", false];
        $headers['ratelimit-reset'] = ["", false];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)
            ->expectStatus(200)
            ->allowExtraHeaders()
            ->expectHeaders($headers)
            ->bodyMatcher(KeysBodyMatcher::init(TestParam::object(
                '{"id":"psc_208e45e48d271294","description":null,"metadata":{},"to":{"id":"adr_' .
                '210a8d4b0b76d77b","description":null,"name":null,"company":"LOB","phone":null,"' .
                'email":null,"address_line1":"210 KING ST STE 6100","address_line2":null,"addres' .
                's_city":"SAN FRANCISCO","address_state":"CA","address_zip":"94107-1741","addres' .
                's_country":"UNITED STATES","metadata":{},"date_created":"2018-12-08T03:01:07.65' .
                '1Z","date_modified":"2018-12-08T03:01:07.651Z","object":"address"},"url":"https' .
                '://lob-assets.com/postcards/psc_208e45e48d271294.pdf?version=v1&expires=1619218' .
                '302&signature=NfHHLBSr5tOHA_Z4kij4dKqZG8f3vMDtwvuFVeeF9pV_lylcjLsVVODhNCE5hR6-2' .
                'slUr6t9WMNsi429Pj7_DA","carrier":"USPS","front_template_id":null,"back_template' .
                '_id":null,"date_created":"2021-03-24T22:51:42.838Z","date_modified":"2021-03-24' .
                'T22:51:42.838Z","send_date":"2021-03-24T22:51:42.838Z","use_type":"marketing","' .
                'object":"postcard"}'
            )))
            ->assert();
    }
}
