<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Tests\Controllers;

use LobLib\Controllers\URLShortenerController;
use LobLib\Exceptions;

class URLShortenerControllerTest extends BaseTestController
{
    /**
     * @var URLShortenerController URLShortenerController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getURLShortenerController();
    }

    public function testDomainList()
    {
        // Perform API call
        $result = null;
        try {
            $result = self::$controller->domainList();
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }

    public function testLinksList()
    {
        // Parameters for the API call
        $limit = 10;
        $offset = 0;
        $mInclude = null;
        $dateCreated = null;
        $metadata = null;
        $campaignId = null;
        $clicked = null;
        $billingGroupId = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->linksList(
                $limit,
                $offset,
                $mInclude,
                $dateCreated,
                $metadata,
                $campaignId,
                $clicked,
                $billingGroupId
            );
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }
}
