<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\Addresses;
use LobLib\Models\Components3;
use LobLib\Models\LocationAnalysis1;

/**
 * Builder for model Addresses
 *
 * @see Addresses
 */
class AddressesBuilder
{
    /**
     * @var Addresses
     */
    private $instance;

    private function __construct(Addresses $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new addresses Builder object.
     */
    public static function init(): self
    {
        return new self(new Addresses());
    }

    /**
     * Sets components field.
     */
    public function components(?Components3 $value): self
    {
        $this->instance->setComponents($value);
        return $this;
    }

    /**
     * Sets location analysis field.
     */
    public function locationAnalysis(?LocationAnalysis1 $value): self
    {
        $this->instance->setLocationAnalysis($value);
        return $this;
    }

    /**
     * Initializes a new addresses object.
     */
    public function build(): Addresses
    {
        return CoreHelper::clone($this->instance);
    }
}
