<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\AddressDeletion;

/**
 * Builder for model AddressDeletion
 *
 * @see AddressDeletion
 */
class AddressDeletionBuilder
{
    /**
     * @var AddressDeletion
     */
    private $instance;

    private function __construct(AddressDeletion $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new address deletion Builder object.
     */
    public static function init(): self
    {
        return new self(new AddressDeletion());
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets deleted field.
     */
    public function deleted(?bool $value): self
    {
        $this->instance->setDeleted($value);
        return $this;
    }

    /**
     * Initializes a new address deletion object.
     */
    public function build(): AddressDeletion
    {
        return CoreHelper::clone($this->instance);
    }
}
