<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\AddressesResponse1;

/**
 * Builder for model AddressesResponse1
 *
 * @see AddressesResponse1
 */
class AddressesResponse1Builder
{
    /**
     * @var AddressesResponse1
     */
    private $instance;

    private function __construct(AddressesResponse1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new addresses response 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new AddressesResponse1());
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets deleted field.
     */
    public function deleted(?bool $value): self
    {
        $this->instance->setDeleted($value);
        return $this;
    }

    /**
     * Initializes a new addresses response 1 object.
     */
    public function build(): AddressesResponse1
    {
        return CoreHelper::clone($this->instance);
    }
}
