<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\BankAccountBase;

/**
 * Builder for model BankAccountBase
 *
 * @see BankAccountBase
 */
class BankAccountBaseBuilder
{
    /**
     * @var BankAccountBase
     */
    private $instance;

    private function __construct(BankAccountBase $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new bank account base Builder object.
     */
    public static function init(
        string $routingNumber,
        string $accountNumber,
        string $accountType,
        string $signatory
    ): self {
        return new self(new BankAccountBase($routingNumber, $accountNumber, $accountType, $signatory));
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Unsets description field.
     */
    public function unsetDescription(): self
    {
        $this->instance->unsetDescription();
        return $this;
    }

    /**
     * Sets check template field.
     */
    public function checkTemplate(?string $value): self
    {
        $this->instance->setCheckTemplate($value);
        return $this;
    }

    /**
     * Sets fractional routing number field.
     */
    public function fractionalRoutingNumber(?string $value): self
    {
        $this->instance->setFractionalRoutingNumber($value);
        return $this;
    }

    /**
     * Sets city field.
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets state field.
     */
    public function state(?string $value): self
    {
        $this->instance->setState($value);
        return $this;
    }

    /**
     * Sets zipcode field.
     */
    public function zipcode(?string $value): self
    {
        $this->instance->setZipcode($value);
        return $this;
    }

    /**
     * Sets metadata field.
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Initializes a new bank account base object.
     */
    public function build(): BankAccountBase
    {
        return CoreHelper::clone($this->instance);
    }
}
