<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\BankAccount;

/**
 * Builder for model BankAccount
 *
 * @see BankAccount
 */
class BankAccountBuilder
{
    /**
     * @var BankAccount
     */
    private $instance;

    private function __construct(BankAccount $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new bank account Builder object.
     */
    public static function init(
        string $routingNumber,
        string $accountNumber,
        string $accountType,
        string $signatory,
        \DateTime $dateCreated,
        \DateTime $dateModified,
        string $id
    ): self {
        return new self(
            new BankAccount(
                $routingNumber,
                $accountNumber,
                $accountType,
                $signatory,
                $dateCreated,
                $dateModified,
                $id
            )
        );
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Unsets description field.
     */
    public function unsetDescription(): self
    {
        $this->instance->unsetDescription();
        return $this;
    }

    /**
     * Sets check template field.
     */
    public function checkTemplate(?string $value): self
    {
        $this->instance->setCheckTemplate($value);
        return $this;
    }

    /**
     * Sets fractional routing number field.
     */
    public function fractionalRoutingNumber(?string $value): self
    {
        $this->instance->setFractionalRoutingNumber($value);
        return $this;
    }

    /**
     * Sets city field.
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets state field.
     */
    public function state(?string $value): self
    {
        $this->instance->setState($value);
        return $this;
    }

    /**
     * Sets zipcode field.
     */
    public function zipcode(?string $value): self
    {
        $this->instance->setZipcode($value);
        return $this;
    }

    /**
     * Sets metadata field.
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets deleted field.
     */
    public function deleted(?bool $value): self
    {
        $this->instance->setDeleted($value);
        return $this;
    }

    /**
     * Sets signature url field.
     */
    public function signatureUrl(?string $value): self
    {
        $this->instance->setSignatureUrl($value);
        return $this;
    }

    /**
     * Unsets signature url field.
     */
    public function unsetSignatureUrl(): self
    {
        $this->instance->unsetSignatureUrl();
        return $this;
    }

    /**
     * Sets bank name field.
     */
    public function bankName(?string $value): self
    {
        $this->instance->setBankName($value);
        return $this;
    }

    /**
     * Sets verified field.
     */
    public function verified(?bool $value): self
    {
        $this->instance->setVerified($value);
        return $this;
    }

    /**
     * Initializes a new bank account object.
     */
    public function build(): BankAccount
    {
        return CoreHelper::clone($this->instance);
    }
}
