<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\BuckslipOrderEditable;

/**
 * Builder for model BuckslipOrderEditable
 *
 * @see BuckslipOrderEditable
 */
class BuckslipOrderEditableBuilder
{
    /**
     * @var BuckslipOrderEditable
     */
    private $instance;

    private function __construct(BuckslipOrderEditable $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new buckslip order editable Builder object.
     */
    public static function init(int $quantity): self
    {
        return new self(new BuckslipOrderEditable($quantity));
    }

    /**
     * Initializes a new buckslip order editable object.
     */
    public function build(): BuckslipOrderEditable
    {
        return CoreHelper::clone($this->instance);
    }
}
