<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\BuckslipOrder;

/**
 * Builder for model BuckslipOrder
 *
 * @see BuckslipOrder
 */
class BuckslipOrderBuilder
{
    /**
     * @var BuckslipOrder
     */
    private $instance;

    private function __construct(BuckslipOrder $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new buckslip order Builder object.
     */
    public static function init(\DateTime $dateCreated, \DateTime $dateModified, string $object): self
    {
        return new self(new BuckslipOrder($dateCreated, $dateModified, $object));
    }

    /**
     * Sets deleted field.
     */
    public function deleted(?bool $value): self
    {
        $this->instance->setDeleted($value);
        return $this;
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets buckslip id field.
     */
    public function buckslipId(?string $value): self
    {
        $this->instance->setBuckslipId($value);
        return $this;
    }

    /**
     * Sets status field.
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets quantity ordered field.
     */
    public function quantityOrdered(?float $value): self
    {
        $this->instance->setQuantityOrdered($value);
        return $this;
    }

    /**
     * Sets unit price field.
     */
    public function unitPrice(?float $value): self
    {
        $this->instance->setUnitPrice($value);
        return $this;
    }

    /**
     * Sets inventory field.
     */
    public function inventory(?float $value): self
    {
        $this->instance->setInventory($value);
        return $this;
    }

    /**
     * Sets cancelled reason field.
     */
    public function cancelledReason(?string $value): self
    {
        $this->instance->setCancelledReason($value);
        return $this;
    }

    /**
     * Sets availability date field.
     */
    public function availabilityDate(?\DateTime $value): self
    {
        $this->instance->setAvailabilityDate($value);
        return $this;
    }

    /**
     * Sets expected availability date field.
     */
    public function expectedAvailabilityDate(?\DateTime $value): self
    {
        $this->instance->setExpectedAvailabilityDate($value);
        return $this;
    }

    /**
     * Initializes a new buckslip order object.
     */
    public function build(): BuckslipOrder
    {
        return CoreHelper::clone($this->instance);
    }
}
