<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\CampaignItem;

/**
 * Builder for model CampaignItem
 *
 * @see CampaignItem
 */
class CampaignItemBuilder
{
    /**
     * @var CampaignItem
     */
    private $instance;

    private function __construct(CampaignItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new campaign item Builder object.
     */
    public static function init(
        string $name,
        array $useType,
        bool $autoCancelIfNcoa,
        string $id,
        bool $isDraft,
        array $creatives,
        array $uploads,
        \DateTime $dateCreated,
        \DateTime $dateModified
    ): self {
        return new self(new CampaignItem(
            $name,
            $useType,
            $autoCancelIfNcoa,
            $id,
            $isDraft,
            $creatives,
            $uploads,
            $dateCreated,
            $dateModified
        ));
    }

    /**
     * Sets billing group id field.
     */
    public function billingGroupId(?string $value): self
    {
        $this->instance->setBillingGroupId($value);
        return $this;
    }

    /**
     * Unsets billing group id field.
     */
    public function unsetBillingGroupId(): self
    {
        $this->instance->unsetBillingGroupId();
        return $this;
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets target delivery date field.
     */
    public function targetDeliveryDate(?\DateTime $value): self
    {
        $this->instance->setTargetDeliveryDate($value);
        return $this;
    }

    /**
     * Unsets target delivery date field.
     */
    public function unsetTargetDeliveryDate(): self
    {
        $this->instance->unsetTargetDeliveryDate();
        return $this;
    }

    /**
     * Sets send date field.
     */
    public function sendDate(?\DateTime $value): self
    {
        $this->instance->setSendDate($value);
        return $this;
    }

    /**
     * Unsets send date field.
     */
    public function unsetSendDate(): self
    {
        $this->instance->unsetSendDate();
        return $this;
    }

    /**
     * Sets cancel window campaign minutes field.
     */
    public function cancelWindowCampaignMinutes(?int $value): self
    {
        $this->instance->setCancelWindowCampaignMinutes($value);
        return $this;
    }

    /**
     * Unsets cancel window campaign minutes field.
     */
    public function unsetCancelWindowCampaignMinutes(): self
    {
        $this->instance->unsetCancelWindowCampaignMinutes();
        return $this;
    }

    /**
     * Sets metadata field.
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets deleted field.
     */
    public function deleted(?bool $value): self
    {
        $this->instance->setDeleted($value);
        return $this;
    }

    /**
     * Initializes a new campaign item object.
     */
    public function build(): CampaignItem
    {
        return CoreHelper::clone($this->instance);
    }
}
