<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\Card;

/**
 * Builder for model Card
 *
 * @see Card
 */
class CardBuilder
{
    /**
     * @var Card
     */
    private $instance;

    private function __construct(Card $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new card Builder object.
     */
    public static function init(
        \DateTime $dateCreated,
        \DateTime $dateModified,
        string $id,
        string $url,
        bool $autoReorder,
        string $rawUrl,
        string $frontOriginalUrl,
        string $backOriginalUrl,
        array $thumbnails,
        int $availableQuantity,
        int $pendingQuantity,
        string $status,
        string $orientation,
        int $thresholdAmount
    ): self {
        return new self(new Card(
            $dateCreated,
            $dateModified,
            $id,
            $url,
            $autoReorder,
            $rawUrl,
            $frontOriginalUrl,
            $backOriginalUrl,
            $thumbnails,
            $availableQuantity,
            $pendingQuantity,
            $status,
            $orientation,
            $thresholdAmount
        ));
    }

    /**
     * Sets deleted field.
     */
    public function deleted(?bool $value): self
    {
        $this->instance->setDeleted($value);
        return $this;
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets size field.
     */
    public function size(?string $value): self
    {
        $this->instance->setSize($value);
        return $this;
    }

    /**
     * Sets reorder quantity field.
     */
    public function reorderQuantity(?int $value): self
    {
        $this->instance->setReorderQuantity($value);
        return $this;
    }

    /**
     * Initializes a new card object.
     */
    public function build(): Card
    {
        return CoreHelper::clone($this->instance);
    }
}
