<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\CardDeletion;

/**
 * Builder for model CardDeletion
 *
 * @see CardDeletion
 */
class CardDeletionBuilder
{
    /**
     * @var CardDeletion
     */
    private $instance;

    private function __construct(CardDeletion $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new card deletion Builder object.
     */
    public static function init(): self
    {
        return new self(new CardDeletion());
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets deleted field.
     */
    public function deleted(?bool $value): self
    {
        $this->instance->setDeleted($value);
        return $this;
    }

    /**
     * Initializes a new card deletion object.
     */
    public function build(): CardDeletion
    {
        return CoreHelper::clone($this->instance);
    }
}
