<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\CardBase;

/**
 * Builder for model CardBase
 *
 * @see CardBase
 */
class CardBaseBuilder
{
    /**
     * @var CardBase
     */
    private $instance;

    private function __construct(CardBase $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new card base Builder object.
     */
    public static function init(): self
    {
        return new self(new CardBase());
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Unsets description field.
     */
    public function unsetDescription(): self
    {
        $this->instance->unsetDescription();
        return $this;
    }

    /**
     * Sets size field.
     */
    public function size(?string $value): self
    {
        $this->instance->setSize($value);
        return $this;
    }

    /**
     * Initializes a new card base object.
     */
    public function build(): CardBase
    {
        return CoreHelper::clone($this->instance);
    }
}
