<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\CardsOrders0Error1;
use LobLib\Models\Error1;

/**
 * Builder for model CardsOrders0Error1
 *
 * @see CardsOrders0Error1
 */
class CardsOrders0Error1Builder
{
    /**
     * @var CardsOrders0Error1
     */
    private $instance;

    private function __construct(CardsOrders0Error1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new cards orders 0 error 1 Builder object.
     */
    public static function init(Error1 $error): self
    {
        return new self(new CardsOrders0Error1($error));
    }

    /**
     * Initializes a new cards orders 0 error 1 object.
     */
    public function build(): CardsOrders0Error1
    {
        return CoreHelper::clone($this->instance);
    }
}
