<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\CompanyInput;

/**
 * Builder for model CompanyInput
 *
 * @see CompanyInput
 */
class CompanyInputBuilder
{
    /**
     * @var CompanyInput
     */
    private $instance;

    private function __construct(CompanyInput $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new company input Builder object.
     */
    public static function init(string $primaryLine, string $city, string $state, string $zipCode): self
    {
        return new self(new CompanyInput($primaryLine, $city, $state, $zipCode));
    }

    /**
     * Sets company field.
     */
    public function company(?string $value): self
    {
        $this->instance->setCompany($value);
        return $this;
    }

    /**
     * Sets secondary line field.
     */
    public function secondaryLine(?string $value): self
    {
        $this->instance->setSecondaryLine($value);
        return $this;
    }

    /**
     * Sets urbanization field.
     */
    public function urbanization(?string $value): self
    {
        $this->instance->setUrbanization($value);
        return $this;
    }

    /**
     * Initializes a new company input object.
     */
    public function build(): CompanyInput
    {
        return CoreHelper::clone($this->instance);
    }
}
