<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\DomainResponse;

/**
 * Builder for model DomainResponse
 *
 * @see DomainResponse
 */
class DomainResponseBuilder
{
    /**
     * @var DomainResponse
     */
    private $instance;

    private function __construct(DomainResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new domain response Builder object.
     */
    public static function init(): self
    {
        return new self(new DomainResponse());
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets domain field.
     */
    public function domain(?string $value): self
    {
        $this->instance->setDomain($value);
        return $this;
    }

    /**
     * Sets account id field.
     */
    public function accountId(?string $value): self
    {
        $this->instance->setAccountId($value);
        return $this;
    }

    /**
     * Initializes a new domain response object.
     */
    public function build(): DomainResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
