<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\IntlComponents;

/**
 * Builder for model IntlComponents
 *
 * @see IntlComponents
 */
class IntlComponentsBuilder
{
    /**
     * @var IntlComponents
     */
    private $instance;

    private function __construct(IntlComponents $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new intl components Builder object.
     */
    public static function init(): self
    {
        return new self(new IntlComponents());
    }

    /**
     * Sets primary number field.
     */
    public function primaryNumber(?string $value): self
    {
        $this->instance->setPrimaryNumber($value);
        return $this;
    }

    /**
     * Sets street name field.
     */
    public function streetName(?string $value): self
    {
        $this->instance->setStreetName($value);
        return $this;
    }

    /**
     * Sets city field.
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets state field.
     */
    public function state(?string $value): self
    {
        $this->instance->setState($value);
        return $this;
    }

    /**
     * Sets postal code field.
     */
    public function postalCode(?string $value): self
    {
        $this->instance->setPostalCode($value);
        return $this;
    }

    /**
     * Initializes a new intl components object.
     */
    public function build(): IntlComponents
    {
        return CoreHelper::clone($this->instance);
    }
}
