<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\IntlSuggestions;

/**
 * Builder for model IntlSuggestions
 *
 * @see IntlSuggestions
 */
class IntlSuggestionsBuilder
{
    /**
     * @var IntlSuggestions
     */
    private $instance;

    private function __construct(IntlSuggestions $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new intl suggestions Builder object.
     */
    public static function init(
        string $primaryNumberRange,
        string $primaryLine,
        string $city,
        string $country,
        string $state,
        string $zipCode
    ): self {
        return new self(new IntlSuggestions($primaryNumberRange, $primaryLine, $city, $country, $state, $zipCode));
    }

    /**
     * Initializes a new intl suggestions object.
     */
    public function build(): IntlSuggestions
    {
        return CoreHelper::clone($this->instance);
    }
}
