<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\LetterEditable;
use LobLib\Models\QrCode4;

/**
 * Builder for model LetterEditable
 *
 * @see LetterEditable
 */
class LetterEditableBuilder
{
    /**
     * @var LetterEditable
     */
    private $instance;

    private function __construct(LetterEditable $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new letter editable Builder object.
     */
    public static function init($to, $from, array $file, bool $color, array $useType): self
    {
        return new self(new LetterEditable($to, $from, $file, $color, $useType));
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Unsets description field.
     */
    public function unsetDescription(): self
    {
        $this->instance->unsetDescription();
        return $this;
    }

    /**
     * Sets metadata field.
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets mail type field.
     */
    public function mailType(?string $value): self
    {
        $this->instance->setMailType($value);
        return $this;
    }

    /**
     * Sets merge variables field.
     */
    public function mergeVariables(?array $value): self
    {
        $this->instance->setMergeVariables($value);
        return $this;
    }

    /**
     * Unsets merge variables field.
     */
    public function unsetMergeVariables(): self
    {
        $this->instance->unsetMergeVariables();
        return $this;
    }

    /**
     * Sets send date field.
     */
    public function sendDate(?array $value): self
    {
        $this->instance->setSendDate($value);
        return $this;
    }

    /**
     * Sets extra service field.
     */
    public function extraService(?array $value): self
    {
        $this->instance->setExtraService($value);
        return $this;
    }

    /**
     * Sets cards field.
     */
    public function cards(?array $value): self
    {
        $this->instance->setCards($value);
        return $this;
    }

    /**
     * Unsets cards field.
     */
    public function unsetCards(): self
    {
        $this->instance->unsetCards();
        return $this;
    }

    /**
     * Sets double sided field.
     */
    public function doubleSided(?bool $value): self
    {
        $this->instance->setDoubleSided($value);
        return $this;
    }

    /**
     * Sets address placement field.
     */
    public function addressPlacement(?string $value): self
    {
        $this->instance->setAddressPlacement($value);
        return $this;
    }

    /**
     * Sets return envelope field.
     */
    public function returnEnvelope(?array $value): self
    {
        $this->instance->setReturnEnvelope($value);
        return $this;
    }

    /**
     * Sets perforated page field.
     */
    public function perforatedPage(?int $value): self
    {
        $this->instance->setPerforatedPage($value);
        return $this;
    }

    /**
     * Unsets perforated page field.
     */
    public function unsetPerforatedPage(): self
    {
        $this->instance->unsetPerforatedPage();
        return $this;
    }

    /**
     * Sets custom envelope field.
     */
    public function customEnvelope(?string $value): self
    {
        $this->instance->setCustomEnvelope($value);
        return $this;
    }

    /**
     * Unsets custom envelope field.
     */
    public function unsetCustomEnvelope(): self
    {
        $this->instance->unsetCustomEnvelope();
        return $this;
    }

    /**
     * Sets billing group id field.
     */
    public function billingGroupId(?string $value): self
    {
        $this->instance->setBillingGroupId($value);
        return $this;
    }

    /**
     * Sets qr code field.
     */
    public function qrCode(?QrCode4 $value): self
    {
        $this->instance->setQrCode($value);
        return $this;
    }

    /**
     * Sets fsc field.
     */
    public function fsc(?bool $value): self
    {
        $this->instance->setFsc($value);
        return $this;
    }

    /**
     * Initializes a new letter editable object.
     */
    public function build(): LetterEditable
    {
        return CoreHelper::clone($this->instance);
    }
}
