<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\LettersResponse;

/**
 * Builder for model LettersResponse
 *
 * @see LettersResponse
 */
class LettersResponseBuilder
{
    /**
     * @var LettersResponse
     */
    private $instance;

    private function __construct(LettersResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new letters response Builder object.
     */
    public static function init(): self
    {
        return new self(new LettersResponse());
    }

    /**
     * Sets id field.
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets deleted field.
     */
    public function deleted(?bool $value): self
    {
        $this->instance->setDeleted($value);
        return $this;
    }

    /**
     * Initializes a new letters response object.
     */
    public function build(): LettersResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
