<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\LobConfidenceScore;

/**
 * Builder for model LobConfidenceScore
 *
 * @see LobConfidenceScore
 */
class LobConfidenceScoreBuilder
{
    /**
     * @var LobConfidenceScore
     */
    private $instance;

    private function __construct(LobConfidenceScore $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new lob confidence score Builder object.
     */
    public static function init(string $level): self
    {
        return new self(new LobConfidenceScore($level));
    }

    /**
     * Sets score field.
     */
    public function score(?float $value): self
    {
        $this->instance->setScore($value);
        return $this;
    }

    /**
     * Initializes a new lob confidence score object.
     */
    public function build(): LobConfidenceScore
    {
        return CoreHelper::clone($this->instance);
    }
}
