<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\Metadata1;

/**
 * Builder for model Metadata1
 *
 * @see Metadata1
 */
class Metadata1Builder
{
    /**
     * @var Metadata1
     */
    private $instance;

    private function __construct(Metadata1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new metadata 1 Builder object.
     */
    public static function init(array $columns): self
    {
        return new self(new Metadata1($columns));
    }

    /**
     * Initializes a new metadata 1 object.
     */
    public function build(): Metadata1
    {
        return CoreHelper::clone($this->instance);
    }
}
