<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\MultipleComponentsList;

/**
 * Builder for model MultipleComponentsList
 *
 * @see MultipleComponentsList
 */
class MultipleComponentsListBuilder
{
    /**
     * @var MultipleComponentsList
     */
    private $instance;

    private function __construct(MultipleComponentsList $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new multiple components list Builder object.
     */
    public static function init(array $addresses): self
    {
        return new self(new MultipleComponentsList($addresses));
    }

    /**
     * Initializes a new multiple components list object.
     */
    public function build(): MultipleComponentsList
    {
        return CoreHelper::clone($this->instance);
    }
}
