<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\OptionalAddressColumnMapping;

/**
 * Builder for model OptionalAddressColumnMapping
 *
 * @see OptionalAddressColumnMapping
 */
class OptionalAddressColumnMappingBuilder
{
    /**
     * @var OptionalAddressColumnMapping
     */
    private $instance;

    private function __construct(OptionalAddressColumnMapping $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new optional address column mapping Builder object.
     */
    public static function init(): self
    {
        return new self(new OptionalAddressColumnMapping());
    }

    /**
     * Sets address line 2 field.
     */
    public function addressLine2(?string $value): self
    {
        $this->instance->setAddressLine2($value);
        return $this;
    }

    /**
     * Sets company field.
     */
    public function company(?string $value): self
    {
        $this->instance->setCompany($value);
        return $this;
    }

    /**
     * Sets address country field.
     */
    public function addressCountry(?string $value): self
    {
        $this->instance->setAddressCountry($value);
        return $this;
    }

    /**
     * Initializes a new optional address column mapping object.
     */
    public function build(): OptionalAddressColumnMapping
    {
        return CoreHelper::clone($this->instance);
    }
}
