<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\QrCodeCampaigns;

/**
 * Builder for model QrCodeCampaigns
 *
 * @see QrCodeCampaigns
 */
class QrCodeCampaignsBuilder
{
    /**
     * @var QrCodeCampaigns
     */
    private $instance;

    private function __construct(QrCodeCampaigns $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new qr code campaigns Builder object.
     */
    public static function init(string $width): self
    {
        return new self(new QrCodeCampaigns($width));
    }

    /**
     * Sets top field.
     */
    public function top(?string $value): self
    {
        $this->instance->setTop($value);
        return $this;
    }

    /**
     * Sets right field.
     */
    public function right(?string $value): self
    {
        $this->instance->setRight($value);
        return $this;
    }

    /**
     * Sets left field.
     */
    public function left(?string $value): self
    {
        $this->instance->setLeft($value);
        return $this;
    }

    /**
     * Sets bottom field.
     */
    public function bottom(?string $value): self
    {
        $this->instance->setBottom($value);
        return $this;
    }

    /**
     * Sets redirect url field.
     */
    public function redirectUrl(?string $value): self
    {
        $this->instance->setRedirectUrl($value);
        return $this;
    }

    /**
     * Sets pages field.
     */
    public function pages(?string $value): self
    {
        $this->instance->setPages($value);
        return $this;
    }

    /**
     * Initializes a new qr code campaigns object.
     */
    public function build(): QrCodeCampaigns
    {
        return CoreHelper::clone($this->instance);
    }
}
