<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\QrCode4;

/**
 * Builder for model QrCode4
 *
 * @see QrCode4
 */
class QrCode4Builder
{
    /**
     * @var QrCode4
     */
    private $instance;

    private function __construct(QrCode4 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new qr code 4 Builder object.
     */
    public static function init(string $redirectUrl, string $width): self
    {
        return new self(new QrCode4($redirectUrl, $width));
    }

    /**
     * Sets top field.
     */
    public function top(?string $value): self
    {
        $this->instance->setTop($value);
        return $this;
    }

    /**
     * Sets right field.
     */
    public function right(?string $value): self
    {
        $this->instance->setRight($value);
        return $this;
    }

    /**
     * Sets left field.
     */
    public function left(?string $value): self
    {
        $this->instance->setLeft($value);
        return $this;
    }

    /**
     * Sets bottom field.
     */
    public function bottom(?string $value): self
    {
        $this->instance->setBottom($value);
        return $this;
    }

    /**
     * Sets pages field.
     */
    public function pages(?string $value): self
    {
        $this->instance->setPages($value);
        return $this;
    }

    /**
     * Initializes a new qr code 4 object.
     */
    public function build(): QrCode4
    {
        return CoreHelper::clone($this->instance);
    }
}
