<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\RequiredAddressColumnMapping;

/**
 * Builder for model RequiredAddressColumnMapping
 *
 * @see RequiredAddressColumnMapping
 */
class RequiredAddressColumnMappingBuilder
{
    /**
     * @var RequiredAddressColumnMapping
     */
    private $instance;

    private function __construct(RequiredAddressColumnMapping $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new required address column mapping Builder object.
     */
    public static function init(): self
    {
        return new self(new RequiredAddressColumnMapping());
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets address line 1 field.
     */
    public function addressLine1(?string $value): self
    {
        $this->instance->setAddressLine1($value);
        return $this;
    }

    /**
     * Sets address city field.
     */
    public function addressCity(?string $value): self
    {
        $this->instance->setAddressCity($value);
        return $this;
    }

    /**
     * Sets address state field.
     */
    public function addressState(?string $value): self
    {
        $this->instance->setAddressState($value);
        return $this;
    }

    /**
     * Sets address zip field.
     */
    public function addressZip(?string $value): self
    {
        $this->instance->setAddressZip($value);
        return $this;
    }

    /**
     * Initializes a new required address column mapping object.
     */
    public function build(): RequiredAddressColumnMapping
    {
        return CoreHelper::clone($this->instance);
    }
}
