<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\Details7;
use LobLib\Models\ReturnedResource2;

/**
 * Builder for model ReturnedResource2
 *
 * @see ReturnedResource2
 */
class ReturnedResource2Builder
{
    /**
     * @var ReturnedResource2
     */
    private $instance;

    private function __construct(ReturnedResource2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new returned resource 2 Builder object.
     */
    public static function init(Details7 $details): self
    {
        return new self(new ReturnedResource2($details));
    }

    /**
     * Sets from field.
     */
    public function from(?array $value): self
    {
        $this->instance->setFrom($value);
        return $this;
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Unsets description field.
     */
    public function unsetDescription(): self
    {
        $this->instance->unsetDescription();
        return $this;
    }

    /**
     * Sets metadata field.
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Initializes a new returned resource 2 object.
     */
    public function build(): ReturnedResource2
    {
        return CoreHelper::clone($this->instance);
    }
}
