<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\QrCode4;
use LobLib\Models\SelfMailerEditable;

/**
 * Builder for model SelfMailerEditable
 *
 * @see SelfMailerEditable
 */
class SelfMailerEditableBuilder
{
    /**
     * @var SelfMailerEditable
     */
    private $instance;

    private function __construct(SelfMailerEditable $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new self mailer editable Builder object.
     */
    public static function init($to, string $inside, string $outside, array $useType): self
    {
        return new self(new SelfMailerEditable($to, $inside, $outside, $useType));
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Unsets description field.
     */
    public function unsetDescription(): self
    {
        $this->instance->unsetDescription();
        return $this;
    }

    /**
     * Sets metadata field.
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets mail type field.
     */
    public function mailType(?string $value): self
    {
        $this->instance->setMailType($value);
        return $this;
    }

    /**
     * Sets merge variables field.
     */
    public function mergeVariables(?array $value): self
    {
        $this->instance->setMergeVariables($value);
        return $this;
    }

    /**
     * Unsets merge variables field.
     */
    public function unsetMergeVariables(): self
    {
        $this->instance->unsetMergeVariables();
        return $this;
    }

    /**
     * Sets send date field.
     */
    public function sendDate(?array $value): self
    {
        $this->instance->setSendDate($value);
        return $this;
    }

    /**
     * Sets size field.
     */
    public function size(?string $value): self
    {
        $this->instance->setSize($value);
        return $this;
    }

    /**
     * Sets from field.
     */
    public function from($value): self
    {
        $this->instance->setFrom($value);
        return $this;
    }

    /**
     * Sets billing group id field.
     */
    public function billingGroupId(?string $value): self
    {
        $this->instance->setBillingGroupId($value);
        return $this;
    }

    /**
     * Sets qr code field.
     */
    public function qrCode(?QrCode4 $value): self
    {
        $this->instance->setQrCode($value);
        return $this;
    }

    /**
     * Sets fsc field.
     */
    public function fsc(?bool $value): self
    {
        $this->instance->setFsc($value);
        return $this;
    }

    /**
     * Initializes a new self mailer editable object.
     */
    public function build(): SelfMailerEditable
    {
        return CoreHelper::clone($this->instance);
    }
}
