<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\SingleLineAddress;

/**
 * Builder for model SingleLineAddress
 *
 * @see SingleLineAddress
 */
class SingleLineAddressBuilder
{
    /**
     * @var SingleLineAddress
     */
    private $instance;

    private function __construct(SingleLineAddress $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new single line address Builder object.
     */
    public static function init(string $address): self
    {
        return new self(new SingleLineAddress($address));
    }

    /**
     * Initializes a new single line address object.
     */
    public function build(): SingleLineAddress
    {
        return CoreHelper::clone($this->instance);
    }
}
