<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\TemplateVersionUpdatable;

/**
 * Builder for model TemplateVersionUpdatable
 *
 * @see TemplateVersionUpdatable
 */
class TemplateVersionUpdatableBuilder
{
    /**
     * @var TemplateVersionUpdatable
     */
    private $instance;

    private function __construct(TemplateVersionUpdatable $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new template version updatable Builder object.
     */
    public static function init(): self
    {
        return new self(new TemplateVersionUpdatable());
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Unsets description field.
     */
    public function unsetDescription(): self
    {
        $this->instance->unsetDescription();
        return $this;
    }

    /**
     * Sets engine field.
     */
    public function engine(?array $value): self
    {
        $this->instance->setEngine($value);
        return $this;
    }

    /**
     * Sets required vars field.
     */
    public function requiredVars(?array $value): self
    {
        $this->instance->setRequiredVars($value);
        return $this;
    }

    /**
     * Initializes a new template version updatable object.
     */
    public function build(): TemplateVersionUpdatable
    {
        return CoreHelper::clone($this->instance);
    }
}
