<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\Thumbnail;

/**
 * Builder for model Thumbnail
 *
 * @see Thumbnail
 */
class ThumbnailBuilder
{
    /**
     * @var Thumbnail
     */
    private $instance;

    private function __construct(Thumbnail $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new thumbnail Builder object.
     */
    public static function init(): self
    {
        return new self(new Thumbnail());
    }

    /**
     * Sets small field.
     */
    public function small(?string $value): self
    {
        $this->instance->setSmall($value);
        return $this;
    }

    /**
     * Sets medium field.
     */
    public function medium(?string $value): self
    {
        $this->instance->setMedium($value);
        return $this;
    }

    /**
     * Sets large field.
     */
    public function large(?string $value): self
    {
        $this->instance->setLarge($value);
        return $this;
    }

    /**
     * Initializes a new thumbnail object.
     */
    public function build(): Thumbnail
    {
        return CoreHelper::clone($this->instance);
    }
}
