<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\Metadata1;
use LobLib\Models\OptionalAddressColumnMapping;
use LobLib\Models\RequiredAddressColumnMapping;
use LobLib\Models\UploadWritable;

/**
 * Builder for model UploadWritable
 *
 * @see UploadWritable
 */
class UploadWritableBuilder
{
    /**
     * @var UploadWritable
     */
    private $instance;

    private function __construct(UploadWritable $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new upload writable Builder object.
     */
    public static function init(string $campaignId): self
    {
        return new self(new UploadWritable($campaignId));
    }

    /**
     * Sets required address column mapping field.
     */
    public function requiredAddressColumnMapping(?RequiredAddressColumnMapping $value): self
    {
        $this->instance->setRequiredAddressColumnMapping($value);
        return $this;
    }

    /**
     * Sets optional address column mapping field.
     */
    public function optionalAddressColumnMapping(?OptionalAddressColumnMapping $value): self
    {
        $this->instance->setOptionalAddressColumnMapping($value);
        return $this;
    }

    /**
     * Sets metadata field.
     */
    public function metadata(?Metadata1 $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets merge variable column mapping field.
     */
    public function mergeVariableColumnMapping(?array $value): self
    {
        $this->instance->setMergeVariableColumnMapping($value);
        return $this;
    }

    /**
     * Unsets merge variable column mapping field.
     */
    public function unsetMergeVariableColumnMapping(): self
    {
        $this->instance->unsetMergeVariableColumnMapping();
        return $this;
    }

    /**
     * Initializes a new upload writable object.
     */
    public function build(): UploadWritable
    {
        return CoreHelper::clone($this->instance);
    }
}
