<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\Metadata1;
use LobLib\Models\OptionalAddressColumnMapping;
use LobLib\Models\RequiredAddressColumnMapping;
use LobLib\Models\Upload;

/**
 * Builder for model Upload
 *
 * @see Upload
 */
class UploadBuilder
{
    /**
     * @var Upload
     */
    private $instance;

    private function __construct(Upload $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new upload Builder object.
     */
    public static function init(
        string $campaignId,
        RequiredAddressColumnMapping $requiredAddressColumnMapping,
        OptionalAddressColumnMapping $optionalAddressColumnMapping,
        Metadata1 $metadata,
        string $id,
        string $accountId,
        string $mode,
        string $state,
        int $totalMailpieces,
        int $failedMailpieces,
        int $validatedMailpieces,
        int $bytesProcessed,
        \DateTime $dateCreated,
        \DateTime $dateModified
    ): self {
        return new self(new Upload(
            $campaignId,
            $requiredAddressColumnMapping,
            $optionalAddressColumnMapping,
            $metadata,
            $id,
            $accountId,
            $mode,
            $state,
            $totalMailpieces,
            $failedMailpieces,
            $validatedMailpieces,
            $bytesProcessed,
            $dateCreated,
            $dateModified
        ));
    }

    /**
     * Sets merge variable column mapping field.
     */
    public function mergeVariableColumnMapping(?array $value): self
    {
        $this->instance->setMergeVariableColumnMapping($value);
        return $this;
    }

    /**
     * Sets failures url field.
     */
    public function failuresUrl(?string $value): self
    {
        $this->instance->setFailuresUrl($value);
        return $this;
    }

    /**
     * Sets original filename field.
     */
    public function originalFilename(?string $value): self
    {
        $this->instance->setOriginalFilename($value);
        return $this;
    }

    /**
     * Initializes a new upload object.
     */
    public function build(): Upload
    {
        return CoreHelper::clone($this->instance);
    }
}
