<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\Wordsatcheckbottom;

/**
 * Builder for model Wordsatcheckbottom
 *
 * @see Wordsatcheckbottom
 */
class WordsatcheckbottomBuilder
{
    /**
     * @var Wordsatcheckbottom
     */
    private $instance;

    private function __construct(Wordsatcheckbottom $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new wordsatcheckbottom Builder object.
     */
    public static function init(string $message, array $useType, $to, $from, string $bankAccount, float $amount): self
    {
        return new self(new Wordsatcheckbottom($message, $useType, $to, $from, $bankAccount, $amount));
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Unsets description field.
     */
    public function unsetDescription(): self
    {
        $this->instance->unsetDescription();
        return $this;
    }

    /**
     * Sets metadata field.
     */
    public function metadata(?array $value): self
    {
        $this->instance->setMetadata($value);
        return $this;
    }

    /**
     * Sets merge variables field.
     */
    public function mergeVariables(?array $value): self
    {
        $this->instance->setMergeVariables($value);
        return $this;
    }

    /**
     * Unsets merge variables field.
     */
    public function unsetMergeVariables(): self
    {
        $this->instance->unsetMergeVariables();
        return $this;
    }

    /**
     * Sets send date field.
     */
    public function sendDate(?array $value): self
    {
        $this->instance->setSendDate($value);
        return $this;
    }

    /**
     * Sets mail type field.
     */
    public function mailType(?string $value): self
    {
        $this->instance->setMailType($value);
        return $this;
    }

    /**
     * Sets memo field.
     */
    public function memo(?string $value): self
    {
        $this->instance->setMemo($value);
        return $this;
    }

    /**
     * Unsets memo field.
     */
    public function unsetMemo(): self
    {
        $this->instance->unsetMemo();
        return $this;
    }

    /**
     * Sets check number field.
     */
    public function checkNumber(?int $value): self
    {
        $this->instance->setCheckNumber($value);
        return $this;
    }

    /**
     * Sets logo field.
     */
    public function logo(?string $value): self
    {
        $this->instance->setLogo($value);
        return $this;
    }

    /**
     * Sets check bottom field.
     */
    public function checkBottom(?array $value): self
    {
        $this->instance->setCheckBottom($value);
        return $this;
    }

    /**
     * Sets attachment field.
     */
    public function attachment(?string $value): self
    {
        $this->instance->setAttachment($value);
        return $this;
    }

    /**
     * Sets billing group id field.
     */
    public function billingGroupId(?string $value): self
    {
        $this->instance->setBillingGroupId($value);
        return $this;
    }

    /**
     * Initializes a new wordsatcheckbottom object.
     */
    public function build(): Wordsatcheckbottom
    {
        return CoreHelper::clone($this->instance);
    }
}
