<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models\Builders;

use Core\Utils\CoreHelper;
use LobLib\Models\Zip5;

/**
 * Builder for model Zip5
 *
 * @see Zip5
 */
class Zip5Builder
{
    /**
     * @var Zip5
     */
    private $instance;

    private function __construct(Zip5 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new zip 5 Builder object.
     */
    public static function init(string $zipCode): self
    {
        return new self(new Zip5($zipCode));
    }

    /**
     * Initializes a new zip 5 object.
     */
    public function build(): Zip5
    {
        return CoreHelper::clone($this->instance);
    }
}
