<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Controllers;

use Core\Request\Parameters\BodyParam;
use Core\Request\Parameters\HeaderParam;
use Core\Response\Types\ErrorType;
use CoreInterfaces\Core\Request\RequestMethod;
use LobLib\Exceptions\ApiException;
use LobLib\Exceptions\Domains0Error1Exception;
use LobLib\Models\CompanyValidation;
use LobLib\Models\RecipientValidation;

class IdentityValidationController extends BaseController
{
    /**
     * Validates whether a given name is associated with an address.
     *
     * @param array $body
     *
     * @return RecipientValidation|CompanyValidation Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function identityValidation(array $body)
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/identity_validation')
            ->auth('basicAuth')
            ->parameters(HeaderParam::init('Content-Type', 'application/json'), BodyParam::init($body));

        $_resHandler = $this->responseHandler()
            ->throwErrorOn('0', ErrorType::init('Error', Domains0Error1Exception::class))
            ->typeGroup('oneOf(RecipientValidation,CompanyValidation)');

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
