<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models;

use stdClass;

class AddressFieldsIntl implements \JsonSerializable
{
    /**
     * @var string
     */
    private $addressLine1;

    /**
     * @var array
     */
    private $addressLine2 = [];

    /**
     * @var array
     */
    private $addressCity = [];

    /**
     * @var array
     */
    private $addressState = [];

    /**
     * @var array
     */
    private $addressZip = [];

    /**
     * @param string $addressLine1
     */
    public function __construct(string $addressLine1)
    {
        $this->addressLine1 = $addressLine1;
    }

    /**
     * Returns Address Line 1.
     * The primary number, street name, and directional information.
     */
    public function getAddressLine1(): string
    {
        return $this->addressLine1;
    }

    /**
     * Sets Address Line 1.
     * The primary number, street name, and directional information.
     *
     * @required
     * @maps address_line1
     */
    public function setAddressLine1(string $addressLine1): void
    {
        $this->addressLine1 = $addressLine1;
    }

    /**
     * Returns Address Line 2.
     * An optional field containing any information which can't fit into line 1.
     */
    public function getAddressLine2(): ?string
    {
        if (count($this->addressLine2) == 0) {
            return null;
        }
        return $this->addressLine2['value'];
    }

    /**
     * Sets Address Line 2.
     * An optional field containing any information which can't fit into line 1.
     *
     * @maps address_line2
     */
    public function setAddressLine2(?string $addressLine2): void
    {
        $this->addressLine2['value'] = $addressLine2;
    }

    /**
     * Unsets Address Line 2.
     * An optional field containing any information which can't fit into line 1.
     */
    public function unsetAddressLine2(): void
    {
        $this->addressLine2 = [];
    }

    /**
     * Returns Address City.
     */
    public function getAddressCity(): ?string
    {
        if (count($this->addressCity) == 0) {
            return null;
        }
        return $this->addressCity['value'];
    }

    /**
     * Sets Address City.
     *
     * @maps address_city
     */
    public function setAddressCity(?string $addressCity): void
    {
        $this->addressCity['value'] = $addressCity;
    }

    /**
     * Unsets Address City.
     */
    public function unsetAddressCity(): void
    {
        $this->addressCity = [];
    }

    /**
     * Returns Address State.
     */
    public function getAddressState(): ?string
    {
        if (count($this->addressState) == 0) {
            return null;
        }
        return $this->addressState['value'];
    }

    /**
     * Sets Address State.
     *
     * @maps address_state
     */
    public function setAddressState(?string $addressState): void
    {
        $this->addressState['value'] = $addressState;
    }

    /**
     * Unsets Address State.
     */
    public function unsetAddressState(): void
    {
        $this->addressState = [];
    }

    /**
     * Returns Address Zip.
     * Optional postal code.
     */
    public function getAddressZip(): ?string
    {
        if (count($this->addressZip) == 0) {
            return null;
        }
        return $this->addressZip['value'];
    }

    /**
     * Sets Address Zip.
     * Optional postal code.
     *
     * @maps address_zip
     */
    public function setAddressZip(?string $addressZip): void
    {
        $this->addressZip['value'] = $addressZip;
    }

    /**
     * Unsets Address Zip.
     * Optional postal code.
     */
    public function unsetAddressZip(): void
    {
        $this->addressZip = [];
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['address_line1']     = $this->addressLine1;
        if (!empty($this->addressLine2)) {
            $json['address_line2'] = $this->addressLine2['value'];
        }
        if (!empty($this->addressCity)) {
            $json['address_city']  = $this->addressCity['value'];
        }
        if (!empty($this->addressState)) {
            $json['address_state'] = $this->addressState['value'];
        }
        if (!empty($this->addressZip)) {
            $json['address_zip']   = $this->addressZip['value'];
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
