<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Unique identifier referring to status of bank account
 */
class BankAccountTypesEnum
{
    public const ENUM_BANK_ACCOUNTCREATED = 'bank_account.created';

    public const ENUM_BANK_ACCOUNTDELETED = 'bank_account.deleted';

    public const ENUM_BANK_ACCOUNTVERIFIED = 'bank_account.verified';

    private const _ALL_VALUES =
        [self::ENUM_BANK_ACCOUNTCREATED, self::ENUM_BANK_ACCOUNTDELETED, self::ENUM_BANK_ACCOUNTVERIFIED];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for BankAccountTypesEnum.");
    }
}
