<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models;

use stdClass;

class BankAccountBase implements \JsonSerializable
{
    /**
     * @var array
     */
    private $description = [];

    /**
     * @var string
     */
    private $routingNumber;

    /**
     * @var string
     */
    private $accountNumber;

    /**
     * @var string
     */
    private $accountType;

    /**
     * @var string
     */
    private $signatory;

    /**
     * @var string|null
     */
    private $checkTemplate;

    /**
     * @var string|null
     */
    private $fractionalRoutingNumber;

    /**
     * @var string|null
     */
    private $city;

    /**
     * @var string|null
     */
    private $state;

    /**
     * @var string|null
     */
    private $zipcode;

    /**
     * @var array<string,string>|null
     */
    private $metadata;

    /**
     * @param string $routingNumber
     * @param string $accountNumber
     * @param string $accountType
     * @param string $signatory
     */
    public function __construct(string $routingNumber, string $accountNumber, string $accountType, string $signatory)
    {
        $this->routingNumber = $routingNumber;
        $this->accountNumber = $accountNumber;
        $this->accountType = $accountType;
        $this->signatory = $signatory;
    }

    /**
     * Returns Description.
     * An internal description that identifies this resource. Must be no longer than 255 characters.
     */
    public function getDescription(): ?string
    {
        if (count($this->description) == 0) {
            return null;
        }
        return $this->description['value'];
    }

    /**
     * Sets Description.
     * An internal description that identifies this resource. Must be no longer than 255 characters.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description['value'] = $description;
    }

    /**
     * Unsets Description.
     * An internal description that identifies this resource. Must be no longer than 255 characters.
     */
    public function unsetDescription(): void
    {
        $this->description = [];
    }

    /**
     * Returns Routing Number.
     * Must be a <a href="https://www.frbservices.org/index.html" target="_blank">valid US routing
     * number</a>.
     */
    public function getRoutingNumber(): string
    {
        return $this->routingNumber;
    }

    /**
     * Sets Routing Number.
     * Must be a <a href="https://www.frbservices.org/index.html" target="_blank">valid US routing
     * number</a>.
     *
     * @required
     * @maps routing_number
     */
    public function setRoutingNumber(string $routingNumber): void
    {
        $this->routingNumber = $routingNumber;
    }

    /**
     * Returns Account Number.
     */
    public function getAccountNumber(): string
    {
        return $this->accountNumber;
    }

    /**
     * Sets Account Number.
     *
     * @required
     * @maps account_number
     */
    public function setAccountNumber(string $accountNumber): void
    {
        $this->accountNumber = $accountNumber;
    }

    /**
     * Returns Account Type.
     */
    public function getAccountType(): string
    {
        return $this->accountType;
    }

    /**
     * Sets Account Type.
     *
     * @required
     * @maps account_type
     * @factory \LobLib\Models\AccountTypeEnum::checkValue
     */
    public function setAccountType(string $accountType): void
    {
        $this->accountType = $accountType;
    }

    /**
     * Returns Signatory.
     * The signatory associated with your account. This name will be printed on checks created with this
     * bank account. If you prefer to use a custom signature image on your checks instead, please create
     * your bank account from the <a href="https://dashboard.lob.com/#/login" target="_blank">Dashboard</a>.
     */
    public function getSignatory(): string
    {
        return $this->signatory;
    }

    /**
     * Sets Signatory.
     * The signatory associated with your account. This name will be printed on checks created with this
     * bank account. If you prefer to use a custom signature image on your checks instead, please create
     * your bank account from the <a href="https://dashboard.lob.com/#/login" target="_blank">Dashboard</a>.
     *
     * @required
     * @maps signatory
     */
    public function setSignatory(string $signatory): void
    {
        $this->signatory = $signatory;
    }

    /**
     * Returns Check Template.
     */
    public function getCheckTemplate(): ?string
    {
        return $this->checkTemplate;
    }

    /**
     * Sets Check Template.
     *
     * @maps check_template
     * @factory \LobLib\Models\CheckTemplateEnum::checkValue
     */
    public function setCheckTemplate(?string $checkTemplate): void
    {
        $this->checkTemplate = $checkTemplate;
    }

    /**
     * Returns Fractional Routing Number.
     * The fractional routing number for your home bank account. Required for the `jpm` check template only.
     * Please contact a bank representative if you do not know the fractional routing number associated
     * with your home bank institution.
     */
    public function getFractionalRoutingNumber(): ?string
    {
        return $this->fractionalRoutingNumber;
    }

    /**
     * Sets Fractional Routing Number.
     * The fractional routing number for your home bank account. Required for the `jpm` check template only.
     * Please contact a bank representative if you do not know the fractional routing number associated
     * with your home bank institution.
     *
     * @maps fractional_routing_number
     */
    public function setFractionalRoutingNumber(?string $fractionalRoutingNumber): void
    {
        $this->fractionalRoutingNumber = $fractionalRoutingNumber;
    }

    /**
     * Returns City.
     * The city associated with your home bank account. Required for the `jpm` check template only. Please
     * contact a bank representative if you do not know the city associated with your home bank institution.
     */
    public function getCity(): ?string
    {
        return $this->city;
    }

    /**
     * Sets City.
     * The city associated with your home bank account. Required for the `jpm` check template only. Please
     * contact a bank representative if you do not know the city associated with your home bank institution.
     *
     * @maps city
     */
    public function setCity(?string $city): void
    {
        $this->city = $city;
    }

    /**
     * Returns State.
     * The state associated with your home bank account. Required for the `jpm` check template only. Please
     * contact a bank representative if you do not know the state associated with your home bank
     * institution.
     */
    public function getState(): ?string
    {
        return $this->state;
    }

    /**
     * Sets State.
     * The state associated with your home bank account. Required for the `jpm` check template only. Please
     * contact a bank representative if you do not know the state associated with your home bank
     * institution.
     *
     * @maps state
     */
    public function setState(?string $state): void
    {
        $this->state = $state;
    }

    /**
     * Returns Zipcode.
     * The zipcode associated with your home bank account. Required for the `jpm` check template only.
     * Please contact a bank representative if you do not know the zipcode associated with your home bank
     * institution.
     */
    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    /**
     * Sets Zipcode.
     * The zipcode associated with your home bank account. Required for the `jpm` check template only.
     * Please contact a bank representative if you do not know the zipcode associated with your home bank
     * institution.
     *
     * @maps zipcode
     */
    public function setZipcode(?string $zipcode): void
    {
        $this->zipcode = $zipcode;
    }

    /**
     * Returns Metadata.
     * Use metadata to store custom information for tagging and labeling back to your internal systems.
     * Must be an object with up to 20 key-value pairs. Keys must be at most 40 characters and values must
     * be at most 500 characters. Neither can contain the characters `"` and `\`. i.e. '{"customer_id" :
     * "NEWYORK2015"}' Nested objects are not supported.  See [Metadata](#section/Metadata) for more
     * information.
     *
     * @return array<string,string>|null
     */
    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    /**
     * Sets Metadata.
     * Use metadata to store custom information for tagging and labeling back to your internal systems.
     * Must be an object with up to 20 key-value pairs. Keys must be at most 40 characters and values must
     * be at most 500 characters. Neither can contain the characters `"` and `\`. i.e. '{"customer_id" :
     * "NEWYORK2015"}' Nested objects are not supported.  See [Metadata](#section/Metadata) for more
     * information.
     *
     * @maps metadata
     *
     * @param array<string,string>|null $metadata
     */
    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->description)) {
            $json['description']               = $this->description['value'];
        }
        $json['routing_number']                = $this->routingNumber;
        $json['account_number']                = $this->accountNumber;
        $json['account_type']                  = AccountTypeEnum::checkValue($this->accountType);
        $json['signatory']                     = $this->signatory;
        if (isset($this->checkTemplate)) {
            $json['check_template']            = CheckTemplateEnum::checkValue($this->checkTemplate);
        }
        if (isset($this->fractionalRoutingNumber)) {
            $json['fractional_routing_number'] = $this->fractionalRoutingNumber;
        }
        if (isset($this->city)) {
            $json['city']                      = $this->city;
        }
        if (isset($this->state)) {
            $json['state']                     = $this->state;
        }
        if (isset($this->zipcode)) {
            $json['zipcode']                   = $this->zipcode;
        }
        if (isset($this->metadata)) {
            $json['metadata']                  = $this->metadata;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
