<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Casing of the verified address. Possible values are `upper` and `proper` for uppercased (e.g. "PO
 * BOX") and proper-cased (e.g. "PO Box"), respectively. Only affects `primary_line`, `city`, and
 * `state`. Default casing is `upper`.
 */
class Case1Enum
{
    public const UPPER = 'upper';

    public const PROPER = 'proper';

    private const _ALL_VALUES = [self::UPPER, self::PROPER];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for Case1Enum.");
    }
}
