<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models;

use stdClass;

/**
 * A nested object containing a breakdown of the deliverability of an address.
 */
class DeliverabilityAnalysis implements \JsonSerializable
{
    /**
     * @var string
     */
    private $dpvConfirmation;

    /**
     * @var string
     */
    private $dpvCmra;

    /**
     * @var string
     */
    private $dpvVacant;

    /**
     * @var string
     */
    private $dpvActive;

    /**
     * @var string[]
     */
    private $dpvFootnotes;

    /**
     * @var bool
     */
    private $ewsMatch;

    /**
     * @var string
     */
    private $lacsIndicator;

    /**
     * @var string
     */
    private $lacsReturnCode;

    /**
     * @var string
     */
    private $suiteReturnCode;

    /**
     * @param string $dpvConfirmation
     * @param string $dpvCmra
     * @param string $dpvVacant
     * @param string $dpvActive
     * @param string[] $dpvFootnotes
     * @param bool $ewsMatch
     * @param string $lacsIndicator
     * @param string $lacsReturnCode
     * @param string $suiteReturnCode
     */
    public function __construct(
        string $dpvConfirmation,
        string $dpvCmra,
        string $dpvVacant,
        string $dpvActive,
        array $dpvFootnotes,
        bool $ewsMatch,
        string $lacsIndicator,
        string $lacsReturnCode,
        string $suiteReturnCode
    ) {
        $this->dpvConfirmation = $dpvConfirmation;
        $this->dpvCmra = $dpvCmra;
        $this->dpvVacant = $dpvVacant;
        $this->dpvActive = $dpvActive;
        $this->dpvFootnotes = $dpvFootnotes;
        $this->ewsMatch = $ewsMatch;
        $this->lacsIndicator = $lacsIndicator;
        $this->lacsReturnCode = $lacsReturnCode;
        $this->suiteReturnCode = $suiteReturnCode;
    }

    /**
     * Returns Dpv Confirmation.
     */
    public function getDpvConfirmation(): string
    {
        return $this->dpvConfirmation;
    }

    /**
     * Sets Dpv Confirmation.
     *
     * @required
     * @maps dpv_confirmation
     * @factory \LobLib\Models\DpvConfirmationEnum::checkValue
     */
    public function setDpvConfirmation(string $dpvConfirmation): void
    {
        $this->dpvConfirmation = $dpvConfirmation;
    }

    /**
     * Returns Dpv Cmra.
     */
    public function getDpvCmra(): string
    {
        return $this->dpvCmra;
    }

    /**
     * Sets Dpv Cmra.
     *
     * @required
     * @maps dpv_cmra
     * @factory \LobLib\Models\DpvCmraEnum::checkValue
     */
    public function setDpvCmra(string $dpvCmra): void
    {
        $this->dpvCmra = $dpvCmra;
    }

    /**
     * Returns Dpv Vacant.
     */
    public function getDpvVacant(): string
    {
        return $this->dpvVacant;
    }

    /**
     * Sets Dpv Vacant.
     *
     * @required
     * @maps dpv_vacant
     * @factory \LobLib\Models\DpvVacantEnum::checkValue
     */
    public function setDpvVacant(string $dpvVacant): void
    {
        $this->dpvVacant = $dpvVacant;
    }

    /**
     * Returns Dpv Active.
     */
    public function getDpvActive(): string
    {
        return $this->dpvActive;
    }

    /**
     * Sets Dpv Active.
     *
     * @required
     * @maps dpv_active
     * @factory \LobLib\Models\DpvActiveEnum::checkValue
     */
    public function setDpvActive(string $dpvActive): void
    {
        $this->dpvActive = $dpvActive;
    }

    /**
     * Returns Dpv Footnotes.
     * An array of 2-character strings that gives more insight into how
     * `deliverability_analysis[dpv_confirmation]` was determined. Will always include at least 1 string,
     * and can include up to 3. For details, see [US Verification Details](#tag/US-Verification-Types).
     *
     * @return string[]
     */
    public function getDpvFootnotes(): array
    {
        return $this->dpvFootnotes;
    }

    /**
     * Sets Dpv Footnotes.
     * An array of 2-character strings that gives more insight into how
     * `deliverability_analysis[dpv_confirmation]` was determined. Will always include at least 1 string,
     * and can include up to 3. For details, see [US Verification Details](#tag/US-Verification-Types).
     *
     * @required
     * @maps dpv_footnotes
     * @factory \LobLib\Models\DpvFootnoteEnum::checkValue
     *
     * @param string[] $dpvFootnotes
     */
    public function setDpvFootnotes(array $dpvFootnotes): void
    {
        $this->dpvFootnotes = $dpvFootnotes;
    }

    /**
     * Returns Ews Match.
     * Indicates whether or not an address has been flagged in the <a href="https://docs.informatica.
     * com/data-engineering/data-engineering-quality/10-4-0/address-validator-port-reference/postal-carrier-
     * certification-data-ports/early-warning-system-return-code.html" target="_blank">Early Warning
     * System</a>, meaning the address is under development and not yet ready to receive mail. However, it
     * should become available in a few months.
     */
    public function getEwsMatch(): bool
    {
        return $this->ewsMatch;
    }

    /**
     * Sets Ews Match.
     * Indicates whether or not an address has been flagged in the <a href="https://docs.informatica.
     * com/data-engineering/data-engineering-quality/10-4-0/address-validator-port-reference/postal-carrier-
     * certification-data-ports/early-warning-system-return-code.html" target="_blank">Early Warning
     * System</a>, meaning the address is under development and not yet ready to receive mail. However, it
     * should become available in a few months.
     *
     * @required
     * @maps ews_match
     */
    public function setEwsMatch(bool $ewsMatch): void
    {
        $this->ewsMatch = $ewsMatch;
    }

    /**
     * Returns Lacs Indicator.
     */
    public function getLacsIndicator(): string
    {
        return $this->lacsIndicator;
    }

    /**
     * Sets Lacs Indicator.
     *
     * @required
     * @maps lacs_indicator
     * @factory \LobLib\Models\LacsIndicatorEnum::checkValue
     */
    public function setLacsIndicator(string $lacsIndicator): void
    {
        $this->lacsIndicator = $lacsIndicator;
    }

    /**
     * Returns Lacs Return Code.
     * A code indicating how `deliverability_analysis[lacs_indicator]` was determined.
     * Possible values are:
     * * `A` — A new address was produced because a match was found in LACS<sup>Link</sup>.
     * * `92` — A LACS<sup>Link</sup> record was matched after dropping secondary information.
     * * `14` — A match was found in LACS<sup>Link</sup>, but could not be converted to a deliverable
     * address.
     * * `00` — A match was not found in LACS<sup>Link</sup>, and no new address was produced.
     * * `''` — LACS<sup>Link</sup> was not attempted.
     */
    public function getLacsReturnCode(): string
    {
        return $this->lacsReturnCode;
    }

    /**
     * Sets Lacs Return Code.
     * A code indicating how `deliverability_analysis[lacs_indicator]` was determined.
     * Possible values are:
     * * `A` — A new address was produced because a match was found in LACS<sup>Link</sup>.
     * * `92` — A LACS<sup>Link</sup> record was matched after dropping secondary information.
     * * `14` — A match was found in LACS<sup>Link</sup>, but could not be converted to a deliverable
     * address.
     * * `00` — A match was not found in LACS<sup>Link</sup>, and no new address was produced.
     * * `''` — LACS<sup>Link</sup> was not attempted.
     *
     * @required
     * @maps lacs_return_code
     */
    public function setLacsReturnCode(string $lacsReturnCode): void
    {
        $this->lacsReturnCode = $lacsReturnCode;
    }

    /**
     * Returns Suite Return Code.
     */
    public function getSuiteReturnCode(): string
    {
        return $this->suiteReturnCode;
    }

    /**
     * Sets Suite Return Code.
     *
     * @required
     * @maps suite_return_code
     * @factory \LobLib\Models\SuiteReturnCodeEnum::checkValue
     */
    public function setSuiteReturnCode(string $suiteReturnCode): void
    {
        $this->suiteReturnCode = $suiteReturnCode;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['dpv_confirmation']  = DpvConfirmationEnum::checkValue($this->dpvConfirmation);
        $json['dpv_cmra']          = DpvCmraEnum::checkValue($this->dpvCmra);
        $json['dpv_vacant']        = DpvVacantEnum::checkValue($this->dpvVacant);
        $json['dpv_active']        = DpvActiveEnum::checkValue($this->dpvActive);
        $json['dpv_footnotes']     = DpvFootnoteEnum::checkValue($this->dpvFootnotes);
        $json['ews_match']         = $this->ewsMatch;
        $json['lacs_indicator']    = LacsIndicatorEnum::checkValue($this->lacsIndicator);
        $json['lacs_return_code']  = $this->lacsReturnCode;
        $json['suite_return_code'] = SuiteReturnCodeEnum::checkValue($this->suiteReturnCode);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
