<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Corresponds to the USPS field `dpv_no_stat`. Indicates that an address has been vacated in the
 * recent past, and is no longer receiving deliveries. If it's been unoccupied for 90+ days, or
 * temporarily vacant, this will be flagged. Possible values are:
 * * `Y` –– Address is active.
 * * `N` –– Address is not active.
 * * `''` –– A DPV match is not made (`deliverability_analysis[dpv_confirmation]` is `N` or an empty
 * string).
 */
class DpvActiveEnum
{
    public const Y = 'Y';

    public const N = 'N';

    private const _ALL_VALUES = [self::Y, self::N];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for DpvActiveEnum.");
    }
}
