<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Unique identifier referring to status of letter
 */
class LetterTypesEnum
{
    public const ENUM_LETTERCREATED = 'letter.created';

    public const ENUM_LETTERRENDERED_PDF = 'letter.rendered_pdf';

    public const ENUM_LETTERRENDERED_THUMBNAILS = 'letter.rendered_thumbnails';

    public const ENUM_LETTERDELETED = 'letter.deleted';

    public const ENUM_LETTERDELIVERED = 'letter.delivered';

    public const ENUM_LETTERFAILED = 'letter.failed';

    public const ENUM_LETTERMAILED = 'letter.mailed';

    public const ENUM_LETTERIN_TRANSIT = 'letter.in_transit';

    public const ENUM_LETTERIN_LOCAL_AREA = 'letter.in_local_area';

    public const ENUM_LETTERINTERNATIONAL_EXIT = 'letter.international_exit';

    public const ENUM_LETTERPROCESSED_FOR_DELIVERY = 'letter.processed_for_delivery';

    public const ENUM_LETTERREROUTED = 'letter.re-routed';

    public const ENUM_LETTERRETURNED_TO_SENDER = 'letter.returned_to_sender';

    public const ENUM_LETTERCERTIFIEDMAILED = 'letter.certified.mailed';

    public const ENUM_LETTERCERTIFIEDIN_TRANSIT = 'letter.certified.in_transit';

    public const ENUM_LETTERCERTIFIEDIN_LOCAL_AREA = 'letter.certified.in_local_area';

    public const ENUM_LETTERCERTIFIEDPROCESSED_FOR_DELIVERY = 'letter.certified.processed_for_delivery';

    public const ENUM_LETTERCERTIFIEDREROUTED = 'letter.certified.re-routed';

    public const ENUM_LETTERCERTIFIEDRETURNED_TO_SENDER = 'letter.certified.returned_to_sender';

    public const ENUM_LETTERCERTIFIEDDELIVERED = 'letter.certified.delivered';

    public const ENUM_LETTERCERTIFIEDPICKUP_AVAILABLE = 'letter.certified.pickup_available';

    public const ENUM_LETTERCERTIFIEDISSUE = 'letter.certified.issue';

    public const ENUM_LETTERRETURN_ENVELOPECREATED = 'letter.return_envelope.created';

    public const ENUM_LETTERRETURN_ENVELOPEDELIVERED = 'letter.return_envelope.delivered';

    public const ENUM_LETTERRETURN_ENVELOPEIN_TRANSIT = 'letter.return_envelope.in_transit';

    public const ENUM_LETTERRETURN_ENVELOPEIN_LOCAL_AREA = 'letter.return_envelope.in_local_area';

    public const ENUM_LETTERRETURN_ENVELOPEINTERNATIONAL_EXIT = 'letter.return_envelope.international_exit';

    public const ENUM_LETTERRETURN_ENVELOPEPROCESSED_FOR_DELIVERY = 'letter.return_envelope.processed_for_delivery';

    public const ENUM_LETTERRETURN_ENVELOPERE_ROUTED = 'letter.return_envelope.re_routed';

    public const ENUM_LETTERRETURN_ENVELOPERETURNED_TO_SENDER = 'letter.return_envelope.returned_to_sender';

    public const ENUM_LETTERVIEWED = 'letter.viewed';

    private const _ALL_VALUES = [
        self::ENUM_LETTERCREATED,
        self::ENUM_LETTERRENDERED_PDF,
        self::ENUM_LETTERRENDERED_THUMBNAILS,
        self::ENUM_LETTERDELETED,
        self::ENUM_LETTERDELIVERED,
        self::ENUM_LETTERFAILED,
        self::ENUM_LETTERMAILED,
        self::ENUM_LETTERIN_TRANSIT,
        self::ENUM_LETTERIN_LOCAL_AREA,
        self::ENUM_LETTERINTERNATIONAL_EXIT,
        self::ENUM_LETTERPROCESSED_FOR_DELIVERY,
        self::ENUM_LETTERREROUTED,
        self::ENUM_LETTERRETURNED_TO_SENDER,
        self::ENUM_LETTERCERTIFIEDMAILED,
        self::ENUM_LETTERCERTIFIEDIN_TRANSIT,
        self::ENUM_LETTERCERTIFIEDIN_LOCAL_AREA,
        self::ENUM_LETTERCERTIFIEDPROCESSED_FOR_DELIVERY,
        self::ENUM_LETTERCERTIFIEDREROUTED,
        self::ENUM_LETTERCERTIFIEDRETURNED_TO_SENDER,
        self::ENUM_LETTERCERTIFIEDDELIVERED,
        self::ENUM_LETTERCERTIFIEDPICKUP_AVAILABLE,
        self::ENUM_LETTERCERTIFIEDISSUE,
        self::ENUM_LETTERRETURN_ENVELOPECREATED,
        self::ENUM_LETTERRETURN_ENVELOPEDELIVERED,
        self::ENUM_LETTERRETURN_ENVELOPEIN_TRANSIT,
        self::ENUM_LETTERRETURN_ENVELOPEIN_LOCAL_AREA,
        self::ENUM_LETTERRETURN_ENVELOPEINTERNATIONAL_EXIT,
        self::ENUM_LETTERRETURN_ENVELOPEPROCESSED_FOR_DELIVERY,
        self::ENUM_LETTERRETURN_ENVELOPERE_ROUTED,
        self::ENUM_LETTERRETURN_ENVELOPERETURNED_TO_SENDER,
        self::ENUM_LETTERVIEWED
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for LetterTypesEnum.");
    }
}
