<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models;

use stdClass;

/**
 * Lob Confidence Score is a nested object that provides a numerical value between 0-100 of the
 * likelihood that an address is deliverable based on Lob’s mail delivery data to over half of US
 * households.
 */
class LobConfidenceScore implements \JsonSerializable
{
    /**
     * @var float|null
     */
    private $score;

    /**
     * @var string
     */
    private $level;

    /**
     * @param string $level
     */
    public function __construct(string $level)
    {
        $this->level = $level;
    }

    /**
     * Returns Score.
     * A numerical score between 0 and 100 that represents the percentage of mailpieces Lob has sent to
     * this addresses that have been delivered successfully over the past 2 years. Will be `null` if no
     * tracking data exists for this address.
     */
    public function getScore(): ?float
    {
        return $this->score;
    }

    /**
     * Sets Score.
     * A numerical score between 0 and 100 that represents the percentage of mailpieces Lob has sent to
     * this addresses that have been delivered successfully over the past 2 years. Will be `null` if no
     * tracking data exists for this address.
     *
     * @maps score
     */
    public function setScore(?float $score): void
    {
        $this->score = $score;
    }

    /**
     * Returns Level.
     */
    public function getLevel(): string
    {
        return $this->level;
    }

    /**
     * Sets Level.
     *
     * @required
     * @maps level
     * @factory \LobLib\Models\LevelEnum::checkValue
     */
    public function setLevel(string $level): void
    {
        $this->level = $level;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['score'] = $this->score;
        $json['level'] = LevelEnum::checkValue($this->level);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
