<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Name of tracking event (for normal postcards, self mailers, letters, and checks):
 *
 * * `Mailed` - The mailpiece has been handed off to and accepted by USPS
 * and is en route. <a href="https://help.lob.com/print-and-mail/getting-data-and-results/tracking-
 * your-mail#mailed-tracking-events-4" target="_blank">More about
 * Mailed.</a>
 * Note this data is only available in Enterprise editions of
 * Lob. <a href="https://lob.com/support/contact#contact" target="_blank">Contact Sales</a> if
 * you want access to this feature.
 *
 * * `In Transit` - The mailpiece is being processed at the entry/origin facility.
 *
 * * `In Local Area` - The mailpiece is being processed at the destination facility.
 *
 * * `Processed for Delivery` - The mailpiece has been greenlit for
 * delivery at the recipient's nearest postal facility. The mailpiece
 * should reach the mailbox within 1 business day of this tracking
 * event.
 *
 * * `Delivered` - The mail piece has been delivered to
 * the recipient’s address. The final scan is generated when the mail
 * carrier's GPS unit leaves the delivery area.
 *
 * * `Re-Routed` - The mailpiece is re-routed due to recipient change of
 * address, address errors, or USPS relabeling of barcode/ID tag
 * area.
 *
 * * `Returned to Sender` - The mailpiece is being returned to sender due
 * to barcode, ID tag area, or address errors.
 *
 * * `International Exit` - The mail piece has been processed to
 * ship to a destination abroad. This is typically the last
 * scan a US-originated international mail piece will receive
 * from the USPS.
 *
 * <a href="https://help.lob.com/print-and-mail/getting-data-and-results/tracking-your-mail#mailed-
 * tracking-events-4" target="_blank">More about tracking</a>
 */
class NameEnum
{
    public const MAILED = 'Mailed';

    public const ENUM_IN_TRANSIT = 'In Transit';

    public const ENUM_IN_LOCAL_AREA = 'In Local Area';

    public const ENUM_PROCESSED_FOR_DELIVERY = 'Processed for Delivery';

    public const DELIVERED = 'Delivered';

    public const REROUTED = 'Re-Routed';

    public const ENUM_RETURNED_TO_SENDER = 'Returned to Sender';

    public const ENUM_INTERNATIONAL_EXIT = 'International Exit';

    private const _ALL_VALUES = [
        self::MAILED,
        self::ENUM_IN_TRANSIT,
        self::ENUM_IN_LOCAL_AREA,
        self::ENUM_PROCESSED_FOR_DELIVERY,
        self::DELIVERED,
        self::REROUTED,
        self::ENUM_RETURNED_TO_SENDER,
        self::ENUM_INTERNATIONAL_EXIT
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for NameEnum.");
    }
}
