<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models;

use stdClass;

class Scans implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $ipLocation;

    /**
     * @var string|null
     */
    private $scanDate;

    /**
     * Returns Ip Location.
     */
    public function getIpLocation(): ?string
    {
        return $this->ipLocation;
    }

    /**
     * Sets Ip Location.
     *
     * @maps ip_location
     */
    public function setIpLocation(?string $ipLocation): void
    {
        $this->ipLocation = $ipLocation;
    }

    /**
     * Returns Scan Date.
     */
    public function getScanDate(): ?string
    {
        return $this->scanDate;
    }

    /**
     * Sets Scan Date.
     *
     * @maps scan_date
     */
    public function setScanDate(?string $scanDate): void
    {
        $this->scanDate = $scanDate;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->ipLocation)) {
            $json['ip_location'] = $this->ipLocation;
        }
        if (isset($this->scanDate)) {
            $json['scan_date']   = $this->scanDate;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
