<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Specifies the size of the self mailer. The `17.75x9_trifold` size is in beta. Contact support@lob.
 * com or your account contact to learn more.
 */
class SelfMailerSizeEnum
{
    public const ENUM_6X18_BIFOLD = '6x18_bifold';

    public const ENUM_11X9_BIFOLD = '11x9_bifold';

    public const ENUM_12X9_BIFOLD = '12x9_bifold';

    public const ENUM_1775X9_TRIFOLD = '17.75x9_trifold';

    private const _ALL_VALUES =
        [self::ENUM_6X18_BIFOLD, self::ENUM_11X9_BIFOLD, self::ENUM_12X9_BIFOLD, self::ENUM_1775X9_TRIFOLD];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for SelfMailerSizeEnum.");
    }
}
