<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models;

use stdClass;

class TemplateVersionWritable implements \JsonSerializable
{
    /**
     * @var array
     */
    private $description = [];

    /**
     * @var string
     */
    private $html;

    /**
     * @var array|null
     */
    private $engine;

    /**
     * @var string[]|null
     */
    private $requiredVars;

    /**
     * @param string $html
     */
    public function __construct(string $html)
    {
        $this->html = $html;
    }

    /**
     * Returns Description.
     * An internal description that identifies this resource. Must be no longer than 255 characters.
     */
    public function getDescription(): ?string
    {
        if (count($this->description) == 0) {
            return null;
        }
        return $this->description['value'];
    }

    /**
     * Sets Description.
     * An internal description that identifies this resource. Must be no longer than 255 characters.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description['value'] = $description;
    }

    /**
     * Unsets Description.
     * An internal description that identifies this resource. Must be no longer than 255 characters.
     */
    public function unsetDescription(): void
    {
        $this->description = [];
    }

    /**
     * Returns Html.
     * An HTML string of less than 100,000 characters to be used as the `published_version` of this
     * template. See [here](#section/HTML-Examples) for guidance on designing HTML templates. Please see
     * endpoint specific documentation for any other product-specific HTML details:
     * - [Postcards](#operation/postcard_create) - `front` and `back`
     * - [Self Mailers](#operation/self_mailer_create) - `inside` and `outside`
     * - [Letters](#operation/letter_create) - `file`
     * - [Checks](#operation/check_create) - `check_bottom` and `attachment`
     * - [Cards](#operation/card_create) - `front` and `back`
     *
     * If there is a syntax error with your variable names within your HTML, then an error will be thrown,
     * e.g. using a `{{#users}}` opening tag without the corresponding closing tag `{{/users}}`.
     */
    public function getHtml(): string
    {
        return $this->html;
    }

    /**
     * Sets Html.
     * An HTML string of less than 100,000 characters to be used as the `published_version` of this
     * template. See [here](#section/HTML-Examples) for guidance on designing HTML templates. Please see
     * endpoint specific documentation for any other product-specific HTML details:
     * - [Postcards](#operation/postcard_create) - `front` and `back`
     * - [Self Mailers](#operation/self_mailer_create) - `inside` and `outside`
     * - [Letters](#operation/letter_create) - `file`
     * - [Checks](#operation/check_create) - `check_bottom` and `attachment`
     * - [Cards](#operation/card_create) - `front` and `back`
     *
     * If there is a syntax error with your variable names within your HTML, then an error will be thrown,
     * e.g. using a `{{#users}}` opening tag without the corresponding closing tag `{{/users}}`.
     *
     * @required
     * @maps html
     */
    public function setHtml(string $html): void
    {
        $this->html = $html;
    }

    /**
     * Returns Engine.
     */
    public function getEngine(): ?array
    {
        return $this->engine;
    }

    /**
     * Sets Engine.
     *
     * @maps engine
     */
    public function setEngine(?array $engine): void
    {
        $this->engine = $engine;
    }

    /**
     * Returns Required Vars.
     * An array of required variables to be used in a template. Only available for `handlebars` templates.
     *
     * @return string[]|null
     */
    public function getRequiredVars(): ?array
    {
        return $this->requiredVars;
    }

    /**
     * Sets Required Vars.
     * An array of required variables to be used in a template. Only available for `handlebars` templates.
     *
     * @maps required_vars
     *
     * @param string[]|null $requiredVars
     */
    public function setRequiredVars(?array $requiredVars): void
    {
        $this->requiredVars = $requiredVars;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->description)) {
            $json['description']   = $this->description['value'];
        }
        $json['html']              = $this->html;
        if (isset($this->engine)) {
            $json['engine']        = $this->engine;
        }
        if (isset($this->requiredVars)) {
            $json['required_vars'] = $this->requiredVars;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
