<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib\Models;

use stdClass;

class Thumbnail implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $small;

    /**
     * @var string|null
     */
    private $medium;

    /**
     * @var string|null
     */
    private $large;

    /**
     * Returns Small.
     * A [signed link](#section/Asset-URLs) served over HTTPS. The link returned will expire in 30 days to
     * prevent mis-sharing. Each time a GET request is initiated, a new signed URL will be generated.
     */
    public function getSmall(): ?string
    {
        return $this->small;
    }

    /**
     * Sets Small.
     * A [signed link](#section/Asset-URLs) served over HTTPS. The link returned will expire in 30 days to
     * prevent mis-sharing. Each time a GET request is initiated, a new signed URL will be generated.
     *
     * @maps small
     */
    public function setSmall(?string $small): void
    {
        $this->small = $small;
    }

    /**
     * Returns Medium.
     * A [signed link](#section/Asset-URLs) served over HTTPS. The link returned will expire in 30 days to
     * prevent mis-sharing. Each time a GET request is initiated, a new signed URL will be generated.
     */
    public function getMedium(): ?string
    {
        return $this->medium;
    }

    /**
     * Sets Medium.
     * A [signed link](#section/Asset-URLs) served over HTTPS. The link returned will expire in 30 days to
     * prevent mis-sharing. Each time a GET request is initiated, a new signed URL will be generated.
     *
     * @maps medium
     */
    public function setMedium(?string $medium): void
    {
        $this->medium = $medium;
    }

    /**
     * Returns Large.
     * A [signed link](#section/Asset-URLs) served over HTTPS. The link returned will expire in 30 days to
     * prevent mis-sharing. Each time a GET request is initiated, a new signed URL will be generated.
     */
    public function getLarge(): ?string
    {
        return $this->large;
    }

    /**
     * Sets Large.
     * A [signed link](#section/Asset-URLs) served over HTTPS. The link returned will expire in 30 days to
     * prevent mis-sharing. Each time a GET request is initiated, a new signed URL will be generated.
     *
     * @maps large
     */
    public function setLarge(?string $large): void
    {
        $this->large = $large;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->small)) {
            $json['small']  = $this->small;
        }
        if (isset($this->medium)) {
            $json['medium'] = $this->medium;
        }
        if (isset($this->large)) {
            $json['large']  = $this->large;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
