<?php

declare(strict_types=1);

/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace LobLib;

/**
 * Environments available for API
 */
class Environment
{
    /**
     * production
     */
    public const PRODUCTION = 'production';
}
